# Canonical Category -> Brand Mapping
# Shared single source of truth for dynamic brands and validation

CATEGORIES = [
    "Mobiles",
    "Electronics",
    "Vehicles",
    "Cycles",
    "Furniture",
    "Fashion",
    "Books",
    "Sports",
    "Home Appliances",
    "Others",
]

CATEGORY_BRAND_MAPPING = {
    "Electronics": [
        "Apple",
        "Samsung",
        "Sony",
        "Dell",
        "HP",
        "Lenovo",
        "Asus",
        "LG",
        "OnePlus",
        "Xiaomi",
        "Realme",
        "Acer",
        "MSI",
    ],
    "Mobiles": [
        "Apple",
        "Samsung",
        "OnePlus",
        "Xiaomi",
        "Realme",
        "Sony",
        "Asus",
        "LG",
    ],
    "Cycles": [
        "Hero",
        "Firefox",
        "Montra",
        "Btwin",
        "Trek",
        "Giant",
        "Scott",
    ],
    "Furniture": [
        "Nilkamal",
        "Godrej",
        "IKEA",
        "Urban Ladder",
        "Wakefit",
        "Durian",
    ],
    "Fashion": [
        "Nike",
        "Adidas",
        "Puma",
        "Zara",
        "H&M",
        "Levi's",
    ],
    "Books": [
        "Penguin Random House",
        "HarperCollins",
        "Macmillan",
        "Simon & Schuster",
        "Hachette",
        "Oxford University Press",
        "Cambridge University Press",
        "Scholastic",
    ],
    "Vehicles": [
        "Toyota",
        "Honda",
        "BMW",
        "Hyundai",
        "Suzuki",
        "Tesla",
        "Mahindra",
        "Tata",
    ],
    "Sports": [
        "Yonex",
        "Cosco",
        "Nivia",
        "SS",
        "MRF",
        "SG",
        "Wilson",
        "Spalding",
        "Decathlon",
    ],
    "Home Appliances": [
        "LG",
        "Samsung",
        "Whirlpool",
        "Bosch",
        "IFB",
        "Godrej",
        "Panasonic",
        "Philips",
    ],
    "Others": [
        "Generic",
        "Handmade",
        "Custom",
        "Unbranded",
    ],
}
